// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6h7KEksgJ3AUyI9JNs73BHebf7DUQmGM',
    appId: '1:955997354464:web:ab3e182836ec489e79d385',
    messagingSenderId: '955997354464',
    projectId: 'prueba-796ad',
    authDomain: 'prueba-796ad.firebaseapp.com',
    storageBucket: 'prueba-796ad.firebasestorage.app',
    measurementId: 'G-R4DH7N4EDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmD9Fn2bQrnQOSZUwTjwcj9reVF0NsSJs',
    appId: '1:955997354464:android:402058c88c1b89a479d385',
    messagingSenderId: '955997354464',
    projectId: 'prueba-796ad',
    storageBucket: 'prueba-796ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2ZzqIxVma4QkKgtES_fVoGw_nGbFo7A',
    appId: '1:955997354464:ios:bd5551c03530b7f179d385',
    messagingSenderId: '955997354464',
    projectId: 'prueba-796ad',
    storageBucket: 'prueba-796ad.firebasestorage.app',
    iosBundleId: 'com.clanship.cliente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh2ZzqIxVma4QkKgtES_fVoGw_nGbFo7A',
    appId: '1:955997354464:ios:bd5551c03530b7f179d385',
    messagingSenderId: '955997354464',
    projectId: 'prueba-796ad',
    storageBucket: 'prueba-796ad.firebasestorage.app',
    iosBundleId: 'com.clanship.cliente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6h7KEksgJ3AUyI9JNs73BHebf7DUQmGM',
    appId: '1:955997354464:web:55bc35511fcfb66279d385',
    messagingSenderId: '955997354464',
    projectId: 'prueba-796ad',
    authDomain: 'prueba-796ad.firebaseapp.com',
    storageBucket: 'prueba-796ad.firebasestorage.app',
    measurementId: 'G-3ELX55CJ1X',
  );
}
